### ISSUE TITLE
Add a wget cell to download the data from the notebook

### ISSUE THREAD

**Issue by jtpio** [jupytercon/2020-exactlyallan#22]
Similar to https://github.com/jupytercon/2020-zronaghi/pull/3, it would be nice to have an easier way to download the data from the the notebook.

One option would be to host the `data.csv` somewhere else, and use `wget` in the notebook to fetch it:

![image](https://user-images.githubusercontent.com/591645/94939648-b7e7d800-04d2-11eb-9fed-c7db7e573b19.png)

Otherwise going to Kaggle, downloading the zip file and uploading it to the notebook server will be tedious, as the file upload size is limited.

**Comment by jtpio** [comment]
@exactlyallan what do you think?

**Comment by AjayThorve** [comment]
@jtpio we are planning to upload the data to s3 and get the wget command within the notebook, should be done soon

**Comment by jtpio** [comment]
Sounds good, thanks!

**Comment by AjayThorve** [comment]
@jtpio added cell to download and extract dataset from s3
![image](https://user-images.githubusercontent.com/20476096/94978160-f2e90c00-04d0-11eb-836a-b0450ab3743b.png)

**Comment by jtpio** [comment]
Nice, thanks!
