### ISSUE TITLE
Memory issue on BinderHub

### ISSUE THREAD

**Issue by jtpio** [jupytercon/2020-exactlyallan#26]
Testing on BinderHub, it looks like we hit a `cudaErrorMemoryAllocation` when running this notebook: https://github.com/jupytercon/2020-exactlyallan/blob/master/notebooks/02%20Exploratory%20Data%20Visualization.ipynb

![image](https://user-images.githubusercontent.com/591645/94985182-90395400-0554-11eb-9db3-1bd996d0780c.png)

The GPU is an Nvidia Tesla V100:

![image](https://user-images.githubusercontent.com/591645/94985176-83b4fb80-0554-11eb-8212-793d72351042.png)

The issue can be mitigated by reducing the size of the dataset with something like this (keeping ~25% of the raw dataset):

```bash
head -n 2500000 data.csv > data-small.csv
```

Maybe there are some code changes that could reduce the GPU memory usage?

cc @AjayThorve @exactlyallan @bryevdv

**Comment by jtpio** [comment]
Here are the specs of the machine where the single user server is running:

![image](https://user-images.githubusercontent.com/591645/95311126-7d44bd80-088d-11eb-9eee-6ca84d8ed970.png)

**Comment by jtpio** [comment]
@AjayThorve @exactlyallan @bryevdv if you want to discuss that more in depth, we can use the Mattermost: https://forum.numfocus.org/

**Comment by bryevdv** [comment]
@jtpio I've joined the mattermost instance, I think I posted comments in the right place, please let me know if you don't see them

**Comment by bryevdv** [comment]
@jtpio I think you've linked the wrong notebook above? The page rank is in 03 not 02

**Comment by bryevdv** [comment]
@jtpio I am unable to repro the OOM above if I make sure to explicitly shut down the previous notebooks first, can you confirm that was the case when you saw this?

**Comment by bryevdv** [comment]
I can generate an OOM in a completely different place, if I leave previous notebooks running (i.e. still taking up GPU resources)

![Screen Shot 2020-10-07 at 11 25 17 AM](https://user-images.githubusercontent.com/1078448/95371992-cdbd1a80-088f-11eb-86a7-ab9cae13c464.png)

**Comment by jtpio** [comment]
ah ok then stopping the running kernels from the previous notebooks might already help.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupytercon/2020-exactlyallan/pull/27
